# Generated by Django 5.0.7 on 2026-09-27 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Tenant', '0013_tenant_show_store_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Người thao tác')),
                ('action', models.CharField(choices=[('auth.login', 'Đăng nhập'), ('auth.logout', 'Đăng xuất'), ('auth.login_failed', 'Đăng nhập thất bại'), ('order.refund', 'Hoàn tiền'), ('order.delete', 'Xoá đơn'), ('order.reprint', 'In lại hoá đơn'), ('shift.open', 'Mở ca'), ('shift.close', 'Chốt ca'), ('cart.void', 'Huỷ món'), ('table.move', 'Chuyển bàn'), ('qr.reject', 'Từ chối đơn QR'), ('kitchen.reprint', 'In lại phiếu bếp'), ('catalog.import', 'Nhập Excel'), ('object.create', 'Tạo mới'), ('object.update', 'Cập nhật'), ('object.delete', 'Xoá')], max_length=40, verbose_name='Thao tác')),
                ('object_type', models.CharField(blank=True, max_length=60, verbose_name='Loại đối tượng')),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Đối tượng')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='Nội dung')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='App_Tenant.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='App_Tenant.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký thao tác',
                'verbose_name_plural': 'Nhật ký thao tác',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='App_Core_au_tenant__43a302_idx'), models.Index(fields=['tenant', 'action', 'created_at'], name='App_Core_au_tenant__2a9c34_idx'), models.Index(fields=['tenant', 'user', 'created_at'], name='App_Core_au_tenant__1484eb_idx')],
            },
        ),
    ]
