# Generated by Django 5.0.1 on 2026-03-13 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Catalog', '0001_initial'),
        ('App_Tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='App_Tenant.tenant')),
            ],
            options={
                'ordering': ['display_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_links', to='App_Catalog.product')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='App_Catalog.topping')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='topping',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uq_topping_tenant_slug'),
        ),
        migrations.AddIndex(
            model_name='producttopping',
            index=models.Index(fields=['product', 'is_active'], name='App_Catalog_product_5bc1af_idx'),
        ),
        migrations.AddIndex(
            model_name='producttopping',
            index=models.Index(fields=['topping', 'is_active'], name='App_Catalog_topping_bb1744_idx'),
        ),
        migrations.AddConstraint(
            model_name='producttopping',
            constraint=models.UniqueConstraint(fields=('product', 'topping'), name='uq_product_topping'),
        ),
    ]
