# Generated by Django 4.2.7 on 2026-04-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Catalog', '0002_topping_producttopping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
    ]
