# Generated by Django 4.2.7 on 2026-04-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Catalog', '0003_remove_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/', verbose_name='Ảnh upload'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_thumbnail',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/thumbs/', verbose_name='Thumbnail'),
        ),
    ]
