# Generated by Django 4.2.7 on 2026-04-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Catalog', '0004_product_image_upload_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='products/_by_tenant/', verbose_name='Ảnh upload'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_thumbnail',
            field=models.ImageField(blank=True, upload_to='products/_by_tenant/thumbs/', verbose_name='Thumbnail'),
        ),
    ]
