# Generated by Django 4.2.7 on 2026-04-04 04:12

import App_Core.tenant_media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Catalog', '0005_product_image_tenant_upload_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=App_Core.tenant_media_paths.product_image_file_upload_to, verbose_name='Ảnh upload'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_thumbnail',
            field=models.ImageField(blank=True, upload_to=App_Core.tenant_media_paths.product_image_thumbnail_upload_to, verbose_name='Thumbnail'),
        ),
    ]
