# Generated by Django 4.2

from __future__ import annotations

import re
from typing import Optional

from django.core.files.base import ContentFile
from django.db import migrations


def _move_on_storage(storage, old_name: str, new_name: str) -> bool:
    if old_name == new_name:
        return True
    if not old_name or not new_name:
        return False
    if storage.exists(new_name) and not storage.exists(old_name):
        return True
    if not storage.exists(old_name):
        return False
    if storage.exists(new_name):
        storage.delete(new_name)
    with storage.open(old_name, 'rb') as src:
        storage.save(new_name, ContentFile(src.read()))
    storage.delete(old_name)
    return True


def _rewrite_product_path(old: str) -> Optional[str]:
    m = re.match(r'^products/tenant_(\d+)/(.*)$', old)
    if m:
        return f'tenant_{m.group(1)}/products/{m.group(2)}'
    return None


def _filefield_path(val) -> str:
    if not val:
        return ''
    if hasattr(val, 'name'):
        return (val.name or '').strip()
    return str(val).strip()


def _rewrite_store_path(old: str, tenant_id) -> Optional[str]:
    m = re.match(r'^store_payment_qr/tenant_(\d+)/(.*)$', old)
    if m:
        return f'tenant_{m.group(1)}/store_payment_qr/{m.group(2)}'
    if tenant_id and old.startswith('store_payment_qr/'):
        rest = old[len('store_payment_qr/') :]
        if rest and not rest.startswith('tenant_'):
            return f'tenant_{tenant_id}/store_payment_qr/{rest}'
    return None


def forwards(apps, schema_editor):
    from django.core.files.storage import default_storage

    storage = default_storage
    Product = apps.get_model('App_Catalog', 'Product')
    Store = apps.get_model('App_Tenant', 'Store')

    for p in Product.objects.all().only('id', 'image_file', 'image_thumbnail').iterator():
        updates = {}
        for field in ('image_file', 'image_thumbnail'):
            old = _filefield_path(getattr(p, field))
            if not old:
                continue
            new = _rewrite_product_path(old)
            if new and new != old and _move_on_storage(storage, old, new):
                updates[field] = new
        if updates:
            Product.objects.filter(pk=p.pk).update(**updates)

    for s in Store.objects.all().only('id', 'tenant_id', 'payment_qr').iterator():
        old = _filefield_path(s.payment_qr)
        if not old:
            continue
        new = _rewrite_store_path(old, s.tenant_id)
        if new and new != old and _move_on_storage(storage, old, new):
            Store.objects.filter(pk=s.pk).update(payment_qr=new)


def backwards(apps, schema_editor):
    from django.core.files.storage import default_storage

    storage = default_storage
    Product = apps.get_model('App_Catalog', 'Product')
    Store = apps.get_model('App_Tenant', 'Store')

    def rev_product(new: str) -> str | None:
        m = re.match(r'^tenant_(\d+)/products/(.*)$', new)
        if m:
            return f'products/tenant_{m.group(1)}/{m.group(2)}'
        return None

    def rev_store(new: str) -> str | None:
        m = re.match(r'^tenant_(\d+)/store_payment_qr/(.*)$', new)
        if m:
            return f'store_payment_qr/tenant_{m.group(1)}/{m.group(2)}'
        return None

    for p in Product.objects.all().only('id', 'image_file', 'image_thumbnail').iterator():
        updates = {}
        for field in ('image_file', 'image_thumbnail'):
            cur = _filefield_path(getattr(p, field))
            if not cur:
                continue
            old = rev_product(cur)
            if old and old != cur and _move_on_storage(storage, cur, old):
                updates[field] = old
        if updates:
            Product.objects.filter(pk=p.pk).update(**updates)

    for s in Store.objects.all().only('id', 'payment_qr').iterator():
        cur = _filefield_path(s.payment_qr)
        if not cur:
            continue
        old = rev_store(cur)
        if old and old != cur and _move_on_storage(storage, cur, old):
            Store.objects.filter(pk=s.pk).update(payment_qr=old)


class Migration(migrations.Migration):

    dependencies = [
        ('App_Catalog', '0006_tenant_root_media_paths'),
        ('App_Tenant', '0003_store_payment_qr_tenant_upload_to'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
