# Generated by Django 5.0.7 on 2026-09-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Catalog', '0010_topping_price_blank'),
        ('App_Tenant', '0017_recipe_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Tên nguyên liệu')),
                ('unit', models.CharField(max_length=20, verbose_name='Đơn vị tính')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Giá vốn / đơn vị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='App_Tenant.tenant')),
            ],
            options={
                'verbose_name': 'Nguyên liệu',
                'verbose_name_plural': 'Nguyên liệu',
                'ordering': ['display_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Định mức')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='App_Catalog.ingredient')),
                ('product_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='App_Catalog.productunit')),
                ('topping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='App_Catalog.topping')),
            ],
            options={
                'verbose_name': 'Định mức nguyên liệu',
                'verbose_name_plural': 'Định mức nguyên liệu',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_ingredient_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('product_unit__isnull', False), ('topping__isnull', True)), models.Q(('product_unit__isnull', True), ('topping__isnull', False)), _connector='OR'), name='ck_recipe_item_single_target'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product_unit__isnull', False)), fields=('product_unit', 'ingredient'), name='uq_recipe_unit_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.UniqueConstraint(condition=models.Q(('topping__isnull', False)), fields=('topping', 'ingredient'), name='uq_recipe_topping_ingredient'),
        ),
    ]
