# Generated by Django 4.2.7 on 2026-04-04 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tenant', '0004_user_tenant_verbose_name'),
        ('App_Accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='App_Tenant.tenant', verbose_name='doanh nghiệp'),
        ),
    ]
