# Generated by Django 5.0.7 on 2026-09-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Accounts', '0004_is_active_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Tên đăng nhập')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='Địa chỉ IP')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='Số lần sai')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần sai gần nhất')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Khoá đến')),
            ],
            options={
                'verbose_name': 'Đăng nhập sai',
                'verbose_name_plural': 'Đăng nhập sai',
                'ordering': ['-last_failure_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='loginattempt',
            constraint=models.UniqueConstraint(fields=('username', 'ip_address'), name='uq_login_attempt_username_ip'),
        ),
    ]
