# Generated by Django 5.0.7 on 2026-09-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Accounts', '0005_login_attempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=40, verbose_name='Hành động')),
                ('key', models.CharField(max_length=150, verbose_name='Khoá')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Số lần')),
                ('window_started_at', models.DateTimeField(verbose_name='Bắt đầu cửa sổ')),
            ],
            options={
                'verbose_name': 'Giới hạn tần suất',
                'verbose_name_plural': 'Giới hạn tần suất',
                'ordering': ['-window_started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='ratelimit',
            constraint=models.UniqueConstraint(fields=('scope', 'key'), name='uq_rate_limit_scope_key'),
        ),
    ]
