# Generated by Django 4.2.7 on 2026-04-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='payment_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_account_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='store_payment_qr/'),
        ),
    ]
