# Generated by Django 4.2.7 on 2026-04-04 01:42

import App_Tenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tenant', '0002_store_payment_qr_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to=App_Tenant.models.store_payment_qr_upload_to),
        ),
    ]
