# Generated by Django 4.2.7 on 2026-04-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tenant', '0003_store_payment_qr_tenant_upload_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'verbose_name': 'Doanh nghiệp', 'verbose_name_plural': 'Doanh nghiệp'},
        ),
    ]
