# Generated by Django 4.2.7 on 2026-04-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tenant', '0005_is_active_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='max_dining_tables',
            field=models.PositiveIntegerField(default=0, help_text='Tổng số bàn (QR/POS) tối đa. 0 = không giới hạn.', verbose_name='Giới hạn bàn'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_staff_users',
            field=models.PositiveIntegerField(default=0, help_text='Số tài khoản nhân viên (không tính quản lý). 0 = không giới hạn.', verbose_name='Giới hạn nhân viên'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_stores',
            field=models.PositiveIntegerField(default=0, help_text='Số cửa hàng tối đa. 0 = không giới hạn.', verbose_name='Giới hạn cửa hàng'),
        ),
    ]
