# Generated by Django 4.2.7 on 2026-04-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tenant', '0007_tenant_limits_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subscription_ends_on',
            field=models.DateField(blank=True, help_text='Để trống khi tạo mới: mặc định 1 năm sau ngày bắt đầu.', null=True, verbose_name='Ngày kết thúc gói'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_starts_on',
            field=models.DateField(blank=True, help_text='Để trống khi tạo mới: hệ thống gán ngày hiện tại.', null=True, verbose_name='Ngày bắt đầu gói'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='max_dining_tables',
            field=models.PositiveIntegerField(blank=True, default=12, help_text='Tổng số bàn (QR/POS) tối đa. 0 = không giới hạn. Mặc định gói mới: 12.', verbose_name='Giới hạn bàn'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='max_staff_users',
            field=models.PositiveIntegerField(blank=True, default=2, help_text='Số tài khoản nhân viên (không tính quản lý). 0 = không giới hạn. Mặc định gói mới: 2.', verbose_name='Giới hạn nhân viên'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='max_stores',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Số cửa hàng tối đa. 0 = không giới hạn. Mặc định gói mới: 1.', verbose_name='Giới hạn cửa hàng'),
        ),
    ]
