# Generated by Django 4.2.7 on 2026-04-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tenant', '0008_tenant_subscription_and_default_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=24, verbose_name='Số điện thoại'),
        ),
    ]
