# Generated by Django 5.0.7 on 2026-09-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tenant', '0011_tenant_topping_qr_feature_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='show_kitchen_feature',
            field=models.BooleanField(default=False, verbose_name='Màn hình bếp (báo bếp)'),
        ),
    ]
