# Generated by Django 5.0.7 on 2026-09-27 03:07

from django.db import migrations, models
from django.db.models import Count


def enable_for_multi_store_tenants(apps, schema_editor):
    # Doanh nghiệp đang có từ 2 cửa hàng trở lên giữ nguyên khả năng quản lý nhiều cửa hàng.
    Tenant = apps.get_model('App_Tenant', 'Tenant')
    tenant_ids = list(
        Tenant.objects.annotate(store_total=Count('stores')).filter(store_total__gt=1).values_list('id', flat=True)
    )
    Tenant.objects.filter(id__in=tenant_ids).update(show_store_feature=True)


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tenant', '0012_tenant_show_kitchen_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='show_store_feature',
            field=models.BooleanField(default=False, help_text='Tắt: doanh nghiệp chỉ dùng 1 cửa hàng mặc định. Bật để mở rộng nhiều cửa hàng (vẫn theo giới hạn gói).', verbose_name='Quản lý nhiều cửa hàng'),
        ),
        migrations.RunPython(enable_for_multi_store_tenants, migrations.RunPython.noop),
    ]
