# Generated by Django 5.0.7 on 2026-09-27 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tenant', '0013_tenant_show_store_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Tên gói')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('price_yearly', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá / năm')),
                ('is_contact_price', models.BooleanField(default=False, help_text='Bật để hiển thị "Liên hệ" thay vì giá cụ thể.', verbose_name='Giá liên hệ')),
                ('tagline', models.CharField(blank=True, max_length=150, verbose_name='Mô tả ngắn')),
                ('highlight', models.CharField(blank=True, help_text='Ví dụ: "Phổ biến nhất".', max_length=60, verbose_name='Nhãn nổi bật')),
                ('max_stores', models.PositiveIntegerField(blank=True, help_text='Để trống = không giới hạn.', null=True, verbose_name='Giới hạn cửa hàng')),
                ('max_staff_users', models.PositiveIntegerField(blank=True, help_text='Để trống = không giới hạn. 0 = không có tài khoản nhân viên (chỉ 1 quản lý).', null=True, verbose_name='Giới hạn nhân viên')),
                ('max_dining_tables', models.PositiveIntegerField(blank=True, help_text='Để trống = không giới hạn.', null=True, verbose_name='Giới hạn bàn')),
                ('max_products', models.PositiveIntegerField(blank=True, help_text='Để trống = không giới hạn.', null=True, verbose_name='Giới hạn món')),
                ('feature_customer', models.BooleanField(default=True, verbose_name='Khách hàng thân thiết')),
                ('feature_promotion', models.BooleanField(default=True, verbose_name='Khuyến mãi')),
                ('feature_qr_order', models.BooleanField(default=True, verbose_name='QR bàn / gọi món QR')),
                ('feature_kitchen', models.BooleanField(default=True, verbose_name='Màn hình bếp')),
                ('is_default', models.BooleanField(default=False, help_text='Gói gán cho doanh nghiệp tự đăng ký tại trang Đăng ký.', verbose_name='Gói đăng ký mặc định')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Gói cước',
                'verbose_name_plural': 'Gói cước',
                'ordering': ['sort_order', 'price_yearly'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_products',
            field=models.PositiveIntegerField(blank=True, help_text='Số món (sản phẩm) tối đa. Để trống = không giới hạn.', null=True, verbose_name='Giới hạn món'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='max_dining_tables',
            field=models.PositiveIntegerField(blank=True, default=12, help_text='Tổng số bàn (QR/POS) tối đa. Để trống = không giới hạn.', null=True, verbose_name='Giới hạn bàn'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='max_staff_users',
            field=models.PositiveIntegerField(blank=True, default=2, help_text='Số tài khoản nhân viên (không tính quản lý). Để trống = không giới hạn, 0 = không có nhân viên.', null=True, verbose_name='Giới hạn nhân viên'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='max_stores',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Số cửa hàng tối đa. Để trống = không giới hạn.', null=True, verbose_name='Giới hạn cửa hàng'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='App_Tenant.subscriptionplan', verbose_name='Gói cước'),
        ),
    ]
