# Generated by Django 5.0.7 on 2026-09-27 15:18

from django.db import migrations, models

# Ca làm việc có từ gói "Cơ bản" trở lên: chỉ gói Miễn phí không có.
# Doanh nghiệp mặc định tắt; quản lý tự bật ở Cấu hình tính năng.
PLANS_WITHOUT_SHIFT = ['mien-phi']


def apply_shift_feature_to_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('App_Tenant', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(slug__in=PLANS_WITHOUT_SHIFT).update(feature_shift=False)


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tenant', '0015_seed_plans_and_null_unlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='feature_shift',
            field=models.BooleanField(default=True, verbose_name='Ca làm việc (chốt ca)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='show_shift_feature',
            field=models.BooleanField(default=False, verbose_name='Ca làm việc (chốt ca)'),
        ),
        migrations.RunPython(apply_shift_feature_to_plans, migrations.RunPython.noop),
    ]
