# Generated by Django 5.0.7 on 2026-09-27 15:27

from django.db import migrations, models

# Định mức nguyên liệu là tính năng nâng cao: chỉ gói "Chuyên nghiệp" trở lên có.
# Doanh nghiệp mặc định tắt; quản lý tự bật ở Cấu hình tính năng.
PLANS_WITHOUT_RECIPE = ['mien-phi', 'co-ban']


def apply_recipe_feature_to_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('App_Tenant', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(slug__in=PLANS_WITHOUT_RECIPE).update(feature_recipe=False)


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tenant', '0016_shift_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='feature_recipe',
            field=models.BooleanField(default=True, verbose_name='Định mức nguyên liệu'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='show_recipe_feature',
            field=models.BooleanField(default=False, verbose_name='Định mức nguyên liệu'),
        ),
        migrations.RunPython(apply_recipe_feature_to_plans, migrations.RunPython.noop),
    ]
