# Generated by Django 5.0.7 on 2026-09-28 10:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tenant', '0017_recipe_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Thuế cộng vào hoá đơn, tính trên số tiền sau giảm giá. 0 = không tính thuế.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('30'))], verbose_name='Thuế (%)'),
        ),
    ]
