# Generated by Django 5.0.1 on 2026-03-12 23:32

import App_Sales.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Catalog', '0001_initial'),
        ('App_Sales', '0001_initial'),
        ('App_Tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('qr_token', models.CharField(default=App_Sales.models.generate_qr_token, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_tables', to='App_Tenant.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_tables', to='App_Tenant.tenant')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QROrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('customer_note', models.CharField(blank=True, max_length=255)),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_qr_orders', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_qr_orders', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_orders', to='App_Tenant.store')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_orders', to='App_Sales.diningtable')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_orders', to='App_Tenant.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QROrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_product_name', models.CharField(max_length=180)),
                ('snapshot_unit_name', models.CharField(max_length=120)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Catalog.product')),
                ('qr_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='App_Sales.qrorder')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Catalog.productunit')),
            ],
        ),
        migrations.CreateModel(
            name='TableCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_product_name', models.CharField(max_length=180)),
                ('snapshot_unit_name', models.CharField(max_length=120)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('STAFF', 'Staff'), ('QR', 'QR')], default='STAFF', max_length=12)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Catalog.product')),
                ('qr_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='App_Sales.qrorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_cart_items', to='App_Tenant.store')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='App_Sales.diningtable')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_cart_items', to='App_Tenant.tenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Catalog.productunit')),
            ],
        ),
        migrations.AddIndex(
            model_name='diningtable',
            index=models.Index(fields=['tenant', 'store', 'is_active'], name='App_Sales_d_tenant__a72289_idx'),
        ),
        migrations.AddIndex(
            model_name='diningtable',
            index=models.Index(fields=['store', 'display_order'], name='App_Sales_d_store_i_769b74_idx'),
        ),
        migrations.AddConstraint(
            model_name='diningtable',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='uq_dining_table_store_code'),
        ),
        migrations.AddIndex(
            model_name='qrorder',
            index=models.Index(fields=['tenant', 'store', 'status', 'created_at'], name='App_Sales_q_tenant__3a16a7_idx'),
        ),
        migrations.AddIndex(
            model_name='qrorder',
            index=models.Index(fields=['table', 'status', 'created_at'], name='App_Sales_q_table_i_938ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='qrorderitem',
            index=models.Index(fields=['qr_order', 'snapshot_product_name'], name='App_Sales_q_qr_orde_f63df2_idx'),
        ),
        migrations.AddIndex(
            model_name='tablecartitem',
            index=models.Index(fields=['tenant', 'store', 'table', 'created_at'], name='App_Sales_t_tenant__44c035_idx'),
        ),
        migrations.AddIndex(
            model_name='tablecartitem',
            index=models.Index(fields=['table', 'source', 'created_at'], name='App_Sales_t_table_i_e383cf_idx'),
        ),
    ]
