# Generated by Django 5.0.1 on 2026-03-13 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Catalog', '0002_topping_producttopping_and_more'),
        ('App_Sales', '0002_diningtable_qrorder_qrorderitem_tablecartitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QROrderItemTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_topping_name', models.CharField(max_length=120)),
                ('snapshot_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('qr_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='App_Sales.qrorderitem')),
                ('topping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Catalog.topping')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TableCartItemTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_topping_name', models.CharField(max_length=120)),
                ('snapshot_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('table_cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='App_Sales.tablecartitem')),
                ('topping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Catalog.topping')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_topping_name', models.CharField(max_length=120)),
                ('snapshot_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='App_Sales.orderitem')),
                ('topping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Catalog.topping')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['order_item', 'snapshot_topping_name'], name='App_Sales_o_order_i_3d9d5e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='orderitemtopping',
            constraint=models.UniqueConstraint(fields=('order_item', 'topping'), name='uq_order_item_topping'),
        ),
        migrations.AddIndex(
            model_name='qrorderitemtopping',
            index=models.Index(fields=['qr_order_item', 'snapshot_topping_name'], name='App_Sales_q_qr_orde_3a38f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='qrorderitemtopping',
            constraint=models.UniqueConstraint(fields=('qr_order_item', 'topping'), name='uq_qr_order_item_topping'),
        ),
        migrations.AddIndex(
            model_name='tablecartitemtopping',
            index=models.Index(fields=['table_cart_item', 'snapshot_topping_name'], name='App_Sales_t_table_c_98e594_idx'),
        ),
        migrations.AddConstraint(
            model_name='tablecartitemtopping',
            constraint=models.UniqueConstraint(fields=('table_cart_item', 'topping'), name='uq_table_cart_item_topping'),
        ),
    ]
