# Generated by Django 5.0.1 on 2026-03-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Sales', '0003_qrorderitemtopping_tablecartitemtopping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
