# Generated by Django 4.2.7 on 2026-04-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Sales', '0004_alter_qrorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningtable',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
    ]
