# Generated by Django 5.0.7 on 2026-09-27 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Catalog', '0010_topping_price_blank'),
        ('App_Sales', '0009_customer_tier_setting_order_tier_discount'),
        ('App_Tenant', '0012_tenant_show_kitchen_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecartitem',
            name='kitchen_sent_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng đã báo bếp'),
        ),
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_name', models.CharField(blank=True, max_length=120, verbose_name='Tên bàn / nhãn phiếu')),
                ('source', models.CharField(choices=[('TABLE', 'Tại bàn'), ('QR', 'Gọi món QR'), ('TAKEAWAY', 'Mang về')], default='TABLE', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_tickets', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_tickets', to='App_Sales.order')),
                ('qr_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_tickets', to='App_Sales.qrorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='App_Tenant.store')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_tickets', to='App_Sales.diningtable')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='App_Tenant.tenant')),
            ],
            options={
                'verbose_name': 'Phiếu bếp',
                'verbose_name_plural': 'Phiếu bếp',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KitchenTicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_product_name', models.CharField(max_length=180)),
                ('snapshot_unit_name', models.CharField(blank=True, max_length=120)),
                ('toppings_text', models.CharField(blank=True, max_length=500)),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ làm'), ('PREPARING', 'Đang làm'), ('DONE', 'Đã xong'), ('CANCELLED', 'Đã huỷ')], default='PENDING', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Catalog.product')),
                ('table_cart_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_items', to='App_Sales.tablecartitem')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='App_Sales.kitchenticket')),
            ],
            options={
                'verbose_name': 'Món trong phiếu bếp',
                'verbose_name_plural': 'Món trong phiếu bếp',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['tenant', 'store', 'completed_at', 'created_at'], name='App_Sales_k_tenant__122aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['table', 'completed_at'], name='App_Sales_k_table_i_636f36_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticketitem',
            index=models.Index(fields=['ticket', 'status'], name='App_Sales_k_ticket__8d1fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticketitem',
            index=models.Index(fields=['table_cart_item', 'status'], name='App_Sales_k_table_c_c5b534_idx'),
        ),
    ]
