# Generated by Django 5.0.7 on 2026-09-27 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Sales', '0010_kitchen_ticket'),
        ('App_Tenant', '0013_tenant_show_store_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenticket',
            name='print_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lần in phiếu'),
        ),
        migrations.AddField(
            model_name='order',
            name='print_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lần in hoá đơn'),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Đã hoàn tiền'),
        ),
        migrations.AddField(
            model_name='order',
            name='table_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Bàn'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Đã hoàn tiền')], default='completed', max_length=20),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Số tiền hoàn')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card/QR')], max_length=20, verbose_name='Hình thức hoàn')),
                ('reason', models.CharField(max_length=255, verbose_name='Lý do')),
                ('is_full', models.BooleanField(default=False, verbose_name='Hoàn toàn bộ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='App_Sales.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='App_Tenant.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='App_Tenant.tenant')),
            ],
            options={
                'verbose_name': 'Hoàn tiền',
                'verbose_name_plural': 'Hoàn tiền',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'store', 'created_at'], name='App_Sales_r_tenant__fcad3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Đang mở'), ('CLOSED', 'Đã chốt')], default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField(verbose_name='Mở ca lúc')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tiền đầu ca')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Chốt ca lúc')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='Số đơn')),
                ('gross_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Doanh thu')),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Thu tiền mặt')),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Thu thẻ/QR')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Giảm giá')),
                ('refund_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Hoàn tiền')),
                ('cash_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Hoàn tiền mặt')),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Tiền mặt dự kiến')),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Tiền mặt thực đếm')),
                ('cash_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Chênh lệch')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Ghi chú')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_shifts', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_shifts', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='App_Tenant.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='App_Tenant.tenant')),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Ca làm việc',
                'ordering': ['-opened_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'store', 'opened_at'], name='App_Sales_s_tenant__949f63_idx'), models.Index(fields=['tenant', 'status'], name='App_Sales_s_tenant__806ff7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('store',), name='uq_open_shift_per_store'),
        ),
    ]
