# Generated by Django 5.0.7 on 2026-09-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Sales', '0011_shift_refund_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrorder',
            name='access_key',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Khoá để khách mang đi xem / sửa / huỷ đơn của mình.', max_length=64),
        ),
        migrations.AddField(
            model_name='qrorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tên khách'),
        ),
        migrations.AddField(
            model_name='qrorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='SĐT khách'),
        ),
        migrations.AddField(
            model_name='qrorder',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'Tại bàn'), ('TAKEAWAY', 'Mang đi')], default='DINE_IN', max_length=12, verbose_name='Loại đơn'),
        ),
        migrations.AddField(
            model_name='qrorder',
            name='sale_order',
            field=models.OneToOneField(blank=True, help_text='Hoá đơn POS đã thu tiền cho đơn mang đi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_order', to='App_Sales.order'),
        ),
        migrations.AlterField(
            model_name='qrorder',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Để trống với đơn mang đi đặt từ trang menu.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_orders', to='App_Sales.diningtable'),
        ),
    ]
