# Generated by Django 5.0.7 on 2026-09-28 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Sales', '0012_qr_takeaway'),
        ('App_Tenant', '0018_tax_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_request_id',
            field=models.CharField(blank=True, editable=False, help_text='Khoá chống tạo đơn trùng khi POS gửi lại cùng một lần thanh toán (bấm đúp, mạng chập chờn).', max_length=64, null=True, verbose_name='Mã yêu cầu thanh toán'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_order_tenant_client_request'),
        ),
    ]
