# Generated by Django 5.2.17 on 2026-09-30 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Sales', '0013_order_client_request_id'),
        ('App_Tenant', '0018_tax_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrorder',
            name='client_request_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Mã yêu cầu đặt món'),
        ),
        migrations.AddField(
            model_name='qrorder',
            name='request_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='qrorder',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_qr_order_tenant_request'),
        ),
    ]
